version: '3'
services:
  ## Banco de dados em Mysql
  db:
    image: mysql:8.0.25
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=softplan
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./softplanBack/docker/volume_mysql:/var/lib/mysql
    links:
      - softplanBack
  
  ## Backend em Spring boot          
  softplanBack:
    build:
      context: ./softplanBack
      dockerfile: ./Dockerfile
    image: murakamibruno/softplanback
    container_name: backend
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - softplanfront

  ## Frontend em angular
  softplanfront:
    container_name: frontend
    build:
      context:  ./softplanFront
      dockerfile: ./Dockerfile
    image: murakamibruno/softplanfront
    ports:
      - '9000:80'

networks:
  softplan-test:
    driver: bridge